name: Build index.json
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build index.json
        run: python build_index.py
      - name: Commit & push index.json (if changed)
        run: |
          set -e
          if [[ -n "$(git status --porcelain index.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.json
            git commit -m "Update index.json [ci skip]"
            git push
          else
            echo "No changes to index.json"
          fi
